@echo off
cd /d d:\URBANLY
echo Adding all files...
git add -A
echo Committing changes...
git commit -m "Enhanced AI: realistic business concepts with financial projections, premium insights with financial data"
echo Setting remote...
git remote add origin https://github.com/divyanshurai27/Urabanly.git 2>nul
echo Pushing to GitHub...
git push -u origin main --force
echo Done!
pause
